

class Orders:

    def __init__(self, **kwargs):
        self.id_testdata = kwargs.get('id_testdata')
        self.URL_tickets = kwargs.get('URL_tickets')
        self.activity = kwargs.get('activity')
        self.first_tickets_type = kwargs.get('first_tickets_type')
        self.second_tickets_type = kwargs.get('second_tickets_type')
        self.third_tickets_type = kwargs.get('third_tickets_type')
        self.fourth_tickets_type = kwargs.get('fourth_tickets_type')
        self.name_first_tickets_type = kwargs.get('name_first_tickets_type')
        self.name_second_tickets_type = kwargs.get('name_second_tickets_type')
        self.name_third_tickets_type = kwargs.get('name_third_tickets_type')
        self.name_fourth_tickets_type = kwargs.get('name_fourth_tickets_type')
        self.year = kwargs.get('year')
        self.month = kwargs.get('month')
        self.day = kwargs.get('day')
        self.time = kwargs.get('time')
        self.first_name = kwargs.get('first_name')
        self.last_name = kwargs.get('last_name')
        self.phone = kwargs.get('phone')
        self.email = kwargs.get('email')
        self.zip_code = kwargs.get('zip_code')
        self.custom_price = kwargs.get('custom_price')
        self.groupon_name = kwargs.get('groupon_name')
        self.promo_code = kwargs.get('promo_code')
        self.gift_certificate_code = kwargs.get('gift_certificate_code')
        self.addon_name = kwargs.get('addon_name')
        self.addon_type = kwargs.get('addon_type')
        self.payment_type = kwargs.get('payment_type')
        self.saved_card = kwargs.get('saved_card')
        self.card_number = kwargs.get('card_number')
        self.declined_card_number = kwargs.get('declined_card_number')
        self.card_date = kwargs.get('card_date')
        self.card_cvc = kwargs.get('card_cvc')
        self.card_zip = kwargs.get('card_zip')
        self.cash_recieved = kwargs.get('cash_recieved')
        self.ticket_total = kwargs.get('ticket_total')
        self.discount = kwargs.get('discount')
        self.gift_certificate = kwargs.get('gift_certificate')
        self.addon = kwargs.get('addon')
        self.taxes = kwargs.get('taxes')
        self.booking_fee = kwargs.get('booking_fee')
        self.grand_total = kwargs.get('grand_total')
        self.URL_cert = kwargs.get('URL_cert')
        self.certificate_type = kwargs.get('certificate_type')
        self.cert_activity = kwargs.get('cert_activity')
        self.cert_first_tickets_type = kwargs.get('cert_first_tickets_type')
        self.cert_second_tickets_type = kwargs.get('cert_second_tickets_type')
        self.cert_third_tickets_type = kwargs.get('cert_third_tickets_type')
        self.cert_fourth_tickets_type = kwargs.get('cert_fourth_tickets_type')
        self.cert_name_first_tickets_type = kwargs.get('cert_name_first_tickets_type')
        self.cert_name_second_tickets_type = kwargs.get('cert_name_second_tickets_type')
        self.cert_name_third_tickets_type = kwargs.get('cert_name_third_tickets_type')
        self.cert_name_fourth_tickets_type = kwargs.get('cert_name_fourth_tickets_type')
        self.initial_amount = kwargs.get('initial_amount')
        self.remain_amount = kwargs.get('remain_amount')
        self.remain_amount_after = kwargs.get('remain_amount_after')
        self.cert_booking_fee = kwargs.get('cert_booking_fee')
        self.cert_total_amount = kwargs.get('cert_total_amount')
        self.cert_charge_type = kwargs.get('cert_charge_type')
        self.cert_check_number = kwargs.get('cert_check_number')
        self.cert_card_number = kwargs.get('cert_card_number')
        self.cert_declined_card_number = kwargs.get('cert_declined_card_number')
        self.cert_card_date = kwargs.get('cert_card_date')
        self.cert_card_cvc = kwargs.get('cert_card_cvc')
        self.cert_card_zip = kwargs.get('cert_card_zip')
        self.bug = kwargs.get('bug')

    def __repr__(self):
        return self.id_testdata if self.bug is None else self.id_testdata + " " + self.bug
